on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    #paths:
      #- "6-deployed-agents/finance/stock-price-agent/agent.py"
      #- "6-deployed-agents/finance/stock-price-agent/Dockerfile"
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: scrtlabs/fetchai-stock-price-agent
    steps:
      - uses: actions/checkout@v4
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Login to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          file: 6-deployed-agents/finance/stock-price-agent/Dockerfile
          context: 6-deployed-agents/finance/stock-price-agent/
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
